### ISSUE TITLE
Issue running docker image

### ISSUE THREAD

**Issue by charlesrwest** [soulteary/docker-gfpgan#1]
Hello!

I'm having some trouble when I try to follow your instructions.  I 

1. Installed docker
2. Ran sudo docker pull soulteary/docker-gfpgan
3. Ran sudo docker run --rm -it -v `pwd`/model/GFPGANCleanv1-NoCE-C2.pth:/GFPGAN.pth -v `pwd`/data:/data soulteary/docker-gfpgan:2022.05.20

I then got the following error message:
`Traceback (most recent call last):
  File "/entrypoint.py", line 22, in <module>
    towhee.glob['path']('*.jpg') 
  File "/opt/conda/lib/python3.9/site-packages/towhee/hparam/hyperparameter.py", line 198, in __call__
    return self._func(*args, **kws)
  File "/opt/conda/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 652, in wrapper
    return self.map(op)
  File "/opt/conda/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 343, in map
    if hasattr(unary_op, 'is_stateful') and unary_op.is_stateful:
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/factory.py", line 121, in is_stateful
    self.__check_init__()
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/factory.py", line 71, in __check_init__
    self._op = op(self._name, self._tag, **self._kws)
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/factory.py", line 50, in op
    op_obj = loader.load_operator(operator_src, kwargs, tag)
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 150, in load_operator
    op = factory(function, args, tag)
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 60, in load_operator_from_registry
    return self.instance_operator(op, args) if op is not None else None
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 160, in instance_operator
    return op(**args) if args is not None else op()
  File "/entrypoint.py", line 13, in __init__
    self._restorer = GFPGANer(model_path, upscale, arch, channel_multiplier, bg_upsampler)
  File "/opt/conda/lib/python3.9/site-packages/gfpgan/utils.py", line 87, in __init__
    loadnet = torch.load(model_path)
  File "/opt/conda/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: '/GFPGAN.pth'
`

I haven't really used docker before, may I ask how to proceed to debug this?

Thanks!

**Comment by soulteary** [comment]
Hi 👋，The reason for this problem is because you forgot to download the model. @charlesrwest 

```bash
[Errno 21] Is a directory: '/GFPGAN.pth'
```

If you are a docker beginner, you can follow the steps of the article to reproduce.
