### ISSUE TITLE
Won't mount in Docker

### ISSUE THREAD

**Issue by thelamedia** [soulteary/docker-gfpgan#2]
After pulling, the models will not mount.  The container exits with the following error: 

`Traceback (most recent call last):
  File "/entrypoint.py", line 22, in <module>
    towhee.glob['path']('*.jpg') 
  File "/opt/conda/lib/python3.9/site-packages/towhee/hparam/hyperparameter.py", line 198, in __call__
    return self._func(*args, **kws)
  File "/opt/conda/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 652, in wrapper
    return self.map(op)
  File "/opt/conda/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 343, in map
    if hasattr(unary_op, 'is_stateful') and unary_op.is_stateful:
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/factory.py", line 121, in is_stateful
    self.__check_init__()
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/factory.py", line 71, in __check_init__
    self._op = op(self._name, self._tag, **self._kws)
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/factory.py", line 50, in op
    op_obj = loader.load_operator(operator_src, kwargs, tag)
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 150, in load_operator
    op = factory(function, args, tag)
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 60, in load_operator_from_registry
    return self.instance_operator(op, args) if op is not None else None
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 160, in instance_operator
    return op(**args) if args is not None else op()
  File "/entrypoint.py", line 13, in __init__
    self._restorer = GFPGANer(model_path, upscale, arch, channel_multiplier, bg_upsampler)
  File "/opt/conda/lib/python3.9/site-packages/gfpgan/utils.py", line 87, in __init__
    loadnet = torch.load(model_path)
  File "/opt/conda/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: '/GFPGAN.pth'
`

**Comment by PeterHaughie** [comment]
```
cd docker-gfpgan/model
wget https://github.com/TencentARC/GFPGAN/releases/download/v0.2.0/GFPGANCleanv1-NoCE-C2.pth
cd ..
docker run --rm -it -v `pwd`/model/GFPGANCleanv1-NoCE-C2.pth:/GFPGAN.pth -v `pwd`/data:/data soulteary/docker-gfpgan:2022.05.20
```

That seemed to sort the issue for me.

**Comment by eisraeli** [comment]
@PeterHaughie It does not resolve the issue.

I had an SELinux issue. It was prevented Docker from accessing the file.
I managed to workaround it using this command:
`docker run --rm -it --security-opt label=type:container_runtime_t -v `pwd`/model/GFPGANCleanv1-NoCE-C2.pth:/GFPGAN.pth -v `pwd`/data:/data soulteary/docker-gfpgan:2022.05.20`

**Comment by PeterHaughie** [comment]
I'm glad you managed to sort the issue your yourself.
