### ISSUE TITLE
IndexError: list index out of range when running

### ISSUE THREAD

**Issue by NuperSu** [soulteary/docker-gfpgan#4]
I have executed commands from the README.md and #2 
```docker pull soulteary/docker-gfpgan```
```cd docker-gfpgan/model```
```wget https://github.com/TencentARC/GFPGAN/releases/download/v0.2.0/GFPGANCleanv1-NoCE-C2.pth```
```cd ..```
```docker run --rm -it -v `pwd`/model/GFPGANCleanv1-NoCE-C2.pth:/GFPGAN.pth -v `pwd`/data:/data soulteary/docker-gfpgan:2022.05.20```
But got this error when running:

` Traceback (most recent call last):
  File "/entrypoint.py", line 22, in <module>
    towhee.glob['path']('*.jpg') 
  File "/opt/conda/lib/python3.9/site-packages/towhee/functional/mixins/display.py", line 157, in show
    header = tuple(contents[0].__dict__) if not header else header
IndexError: list index out of range`
Is there any way to fix it?

**Comment by NuperSu** [comment]
Seams like it it because of data folder having no images. So coping images solves the problem.

**Comment by eisraeli** [comment]
I'm still getting the `IndexError: list index out or range` even when the `data` folder is populated with a `jpg`:
```
/opt/conda/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "/entrypoint.py", line 22, in <module>
    towhee.glob['path']('*.jpg') 
  File "/opt/conda/lib/python3.9/site-packages/towhee/functional/mixins/display.py", line 154, in show
    contents = [x for i, x in enumerate(self._iterable) if i < limit]
  File "/opt/conda/lib/python3.9/site-packages/towhee/functional/mixins/display.py", line 154, in <listcomp>
    contents = [x for i, x in enumerate(self._iterable) if i < limit]
  File "/opt/conda/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 361, in inner
    return unary_op(x)
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/factory.py", line 95, in __call__
    res = self.__apply__(*arg, **kws)
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/factory.py", line 78, in __apply__
    return self._op(*args, **kws)
  File "/opt/conda/lib/python3.9/site-packages/towhee/engine/operator_registry.py", line 192, in wrapper_call
    return old_call(self, *args, **kws)
  File "/entrypoint.py", line 19, in __call__
    return restored_faces[0][:, :, ::-1]
IndexError: list index out of range
```
